# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://pvsnp-hash.github.io/python_bootcamp/"

git_url = "https://github.com/pvsnp-hash/python_bootcamp/tree/master/"

def custom_doc_links(name): return None
